name: Dose
favicon: null
layout_spectrum: 0.7197994687594473
typography_spectrum: 0.8441676623187959
title: Test site because I can
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e5eaee'
    - '#932d2a'
    - '#8c8c8c'
    - '#b0b5b9'
  brandStrength: 0.5726908145006746
  lightness: 0.25
  saturation: 0.06781379086896777
  rhythmicContrast: 0.30885066580958664
purpose: []
